#!/bin/bash

# Created by argbash-init v2.5.1
# ARG_OPTIONAL_SINGLE([credentials],[s],[path to credentials json file],[$PWD/org.dcs.iot.kaa.client/src/test/resources/kaaCredentials.yaml])
# ARG_OPTIONAL_SINGLE([config],[o],[path to config directory],[$PWD/org.dcs.iot.kaa.client/src/test/resources/kaa-config])
# ARG_HELP([Script to initialise a Kaa IoT Instance with DCS credentials and configuration])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.5.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}

begins_with_short_option()
{
	local first_option all_short_options
	all_short_options='soh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}



# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_credentials="$PWD/org.dcs.iot.kaa.client/src/test/resources/kaaCredentials.yaml"
_arg_config="$PWD/org.dcs.iot.kaa.client/src/test/resources/kaa-config"

print_help ()
{
	printf "%s\n" "Script to initialise a Kaa IoT Instance with DCS credentials and configuration"
	printf 'Usage: %s [-s|--credentials <arg>] [-o|--config <arg>] [-h|--help]\n' "$0"
	printf "\t%s\n" "-s,--credentials: path to credentials json file (default: '"$PWD/org.dcs.iot.kaa.client/src/test/resources/kaaCredentials.yaml"')"
	printf "\t%s\n" "-o,--config: path to config directory (default: '"$PWD/org.dcs.iot.kaa.client/src/test/resources/kaa-config"')"
	printf "\t%s\n" "-h,--help: Prints help"
}

parse_commandline ()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-s|--credentials)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_credentials="$2"
				shift
				;;
			--credentials=*)
				_arg_credentials="${_key##--credentials=}"
				;;
			-s*)
				_arg_credentials="${_key##-s}"
				;;
			-o|--config)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_config="$2"
				shift
				;;
			--config=*)
				_arg_config="${_key##--config=}"
				;;
			-o*)
				_arg_config="${_key##-o}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

sbt -DkaaCredentials=$_arg_credentials \
    -DkaaConfigDir=$_arg_config \
    "kaaiot-client/runMain org.dcs.iot.kaa.KaaIoTInitialiser"

# ] <-- needed because of Argbash
